# para acessar o banco de dados
# http://localhost:8080/h2-console
# coloca URL jdbc:h2:mem disponivel no log da aplicação
spring:
  datasource:
    url: jdbc:h2:mem:crs_db
    username: danilo
    password: 1234
  #ddl é conjunto de instruções do banco create, drop etc
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false