# para acessar o banco de dados
# http://localhost:8080/h2-console
# coloca URL jdbc:h2:mem disponível no log da aplicação
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false